name = "festabot-catalunya"
main = "src/index.ts"
compatibility_date = "2026-07-21"
workers_dev = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "festabot-catalunya"
database_id = "b26c0105-4092-4474-a607-ecfaff1474f2"

[triggers]
crons = ["*/5 * * * *"]

[[ratelimits]]
name = "USER_RATE_LIMITER"
namespace_id = "741826103"

[ratelimits.simple]
limit = 30
period = 60
